backend:
  name: git-gateway
  branch: main

media_folder: "public/img/plante"
public_folder: "/img/plante"

collections:
  - name: "plante"
    label: "Plante"
    folder: "content/plante"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nume", name: "nume", widget: "string" }
      - { label: "Descriere", name: "descriere", widget: "text" }
      - { label: "Preț", name: "pret", widget: "number" }
      - { label: "Imagine", name: "imagine", widget: "image" }
